# AWS CpdeDeploy 설정

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step4
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: root

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: root